const propertyScope = {
	architecture: 'Owned',
	bespokeMonitoring: 'Owned',
	code: 'Excluded',
	containsPersonalData: 'Owned',
	containsSensitiveData: 'Owned',
	dataRecoveryDetails: 'Owned',
	dataRecoveryProcessType: 'Owned',
	deliveredBy: 'Owned',
	dependentCapabilities: 'Excluded',
	dependentProducts: 'Excluded',
	dependents: 'Excluded',
	description: 'Essential',
	failbackProcessType: 'Owned',
	failoverArchitectureType: 'Owned',
	failoverDetails: 'Owned',
	failoverProcessType: 'Owned',
	firstLineTroubleshooting: 'Owned',
	healthchecks: 'Owned',
	hostPlatform: 'Owned',
	keyManagementDetails: 'Owned',
	keyManagementProcessType: 'Owned',
	knownAboutBy: 'Owned',
	lastServiceReviewDate: 'Excluded',
	lastSOSReport: 'Excluded',
	lifecycleStage: 'Owned',
	moreInformation: 'Owned',
	name: 'Essential',
	piiSources: 'Excluded',
	primaryUrl: 'Owned',
	recursiveDependencies: 'Excluded',
	recursiveDependentProducts: 'Excluded',
	recursiveDependents: 'Excluded',
	releaseDetails: 'Owned',
	releaseProcessType: 'Owned',
	replacedBy: 'Excluded',
	repositories: 'Excluded',
	rollbackProcessType: 'Owned',
	secondLineTroubleshooting: 'Owned',
	serviceTier: 'Essential',
	SF_ID: 'Excluded',
	sosTrafficLight: 'Excluded',
	stakeholders: 'Excluded',
	supportedBy: 'Owned',
	updatesData: 'Excluded',
};

const matchingProperties = desiredScope =>
	Object.entries(propertyScope)
		.filter(([, scope]) => scope === desiredScope)
		.map(([property]) => property);

module.exports = {
	propertyScope,
	owned: matchingProperties('Owned'),
	essential: matchingProperties('Essential'),
	excluded: matchingProperties('Excluded'),
};
